### PR TITLE
reverse proxy server

### PR DESCRIPTION
**Pull request by HenryChen-CH**
Implement Proxy Handler. 
synchronous http client, support http1.0 only
fix a bug in longest prefix matching: "/" 
proxy path for proxy handler should always be /, and no other handlers exist

### CODE REVIEW

**Comment by haoxiangzhx** [comment]
Your team's implementation works well! But it it better to write unit test and integration test for the new request handler.

**Comment by HenryChen-CH** [comment]
It is good that it works! We will write test for it very soon.

**Comment by haoxiangzhx** [comment]
Great! Also, if you guys have time, it is better to add some more comments to the code.

**Comment by Shuang-Wang** [comment]
All seem to be working well! I'm ready to merge it into the master branch. Thank you and kudos for the nice work!

**Pull request merged**
